version: '2.3.0'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/home/user/monitoring/prometheus  # prometheus.yml이 있는 디렉토리 연결
    command:
      - "--config.file=/home/user/monitoring/prometheus/prometheus.yaml"
    restart: unless-stopped

  nvidia:
    image: nvidia/dcgm-exporter:3.3.8-3.6.0-ubuntu22.04
    container_name: nvidia
    ports:
      - "9400:9400"
    runtime: nvidia
    environment:
      - DCGM_HOSTENGINE=enabled
    cap_add:
      - SYS_ADMIN
    restart: unless-stopped

  dcgm:
    image: mindprince/nvidia_gpu_prometheus_exporter:0.1
    container_name: dcgm
    ports:
      - "9445:9445"
    runtime: nvidia
    environment:
      - DCGM_HOSTENGINE=enabled
    cap_add:
      - SYS_ADMIN
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana  # Grafana 데이터 저장 경로
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Grafana 관리자 비밀번호 설정
    restart: unless-stopped
 
  # tensorflow:
  #   image: duddlf456/tensorflow_pytorch:gpu-jupyter
  #   runtime: nvidia
  #   container_name: tensorflow
  #   environment:
  #     - NVIDIA_VISIBLE_DEVICES=all
  #     - JUPYTER_TOKEN=G0_evnGAuPPKvfb0dCEVbg  # Jupyter 노트북 접근을 위한 토큰 설정
  #   ports:
  #     - "8888:8888"  # Jupyter 노트북 포트
  #   volumes:
  #     - ./tensorflow:/tf/notebooks  # 현재 디렉토리의 notebooks 폴더를 컨테이너와 공유
  #   command: >
  #     jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token=G0_evnGAuPPKvfb0dCEVbg
  #   restart: unless-stopped

      #  pytorch:
        #  image: pytorch/pytorch:latest
        #  container_name: pytorch
        #  volumes:
        #   - ./pytorch:/workspace
        # command: tail -f /dev/null  # 컨테이너가 계속 실행되도록 유지
        # restart: unless-stopped
