global:
  scrape_interval: 3s  # 기본 scrape 간격을 5초로 설정
  evaluation_interval: 3s  # 규칙 평가 간격

scrape_configs:
  - job_name: 'dcgm'
    scrape_interval: 3s  # dcgm job의 scrape 간격을 5초로 설정
    static_configs:
      - targets: ['dcgm:9445']  # dcgm exporter의 주소

  - job_name: 'nvidia'
    scrape_interval: 3s  # dcgm job의 scrape 간격을 5초로 설정
    static_configs:
      - targets: ['nvidia:9400']  # dcgm exporter의 주소

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']